# Auto-label PRs based on changed files

'area:api':
  - 'src/routes/**/*'
  - 'src/app/**/*'

'area:proxy':
  - 'src/routes/proxy.ts'
  - 'src/lib/httpClient.ts'
  - 'src/lib/coreVerificationClient.ts'

'area:middleware':
  - 'src/middleware/**/*'

'area:config':
  - 'src/config/**/*'
  - '.env*'
  - 'tsconfig.json'

'area:tests':
  - 'tests/**/*'
  - '**/*.test.ts'
  - '**/*.spec.ts'
  - 'jest.config.js'

'type:docs':
  - '**/*.md'
  - 'docs/**/*'

'type:deps':
  - 'package.json'
  - 'package-lock.json'

'type:test':
  - 'tests/**/*'
  - '**/*.test.ts'
  - '**/*.spec.ts'
