# Backend Labels
- name: 'team:backend'
  color: '0E8A16'
  description: 'Backend team'

- name: 'area:api'
  color: 'D4C5F9'
  description: 'API endpoints and routes'

- name: 'area:proxy'
  color: 'D4C5F9'
  description: 'Proxy and gateway functionality'

- name: 'area:middleware'
  color: 'D4C5F9'
  description: 'Express middleware'

- name: 'area:config'
  color: 'D4C5F9'
  description: 'Configuration and environment'

- name: 'area:tests'
  color: 'D4C5F9'
  description: 'Test files and testing infrastructure'

# Type Labels
- name: 'type:feature'
  color: 'FBCA04'
  description: 'New feature or enhancement'

- name: 'type:bugfix'
  color: 'D93F0B'
  description: 'Bug fix'

- name: 'type:refactor'
  color: '5319E7'
  description: 'Code refactoring'

- name: 'type:test'
  color: '0E8A16'
  description: 'Test additions or fixes'

- name: 'type:docs'
  color: 'FBCA04'
  description: 'Documentation update'

- name: 'type:deps'
  color: '0366D6'
  description: 'Dependency updates'

# Priority Labels
- name: 'priority:critical'
  color: 'D93F0B'
  description: 'Critical priority'

- name: 'priority:high'
  color: 'FBCA04'
  description: 'High priority'

- name: 'priority:medium'
  color: 'C2E0C6'
  description: 'Medium priority'

- name: 'priority:low'
  color: 'F9D0C4'
  description: 'Low priority'

# Status Labels
- name: 'status:needs-review'
  color: 'F9D0C4'
  description: 'Needs code review'

- name: 'status:blocked'
  color: 'D93F0B'
  description: 'Blocked by external dependency'

- name: 'status:in-progress'
  color: 'C2E0C6'
  description: 'Work in progress'

- name: 'status:ready-to-merge'
  color: '0E8A16'
  description: 'Ready to merge'
